### ISSUE TITLE
UNIQURL IS NOT WORKING WITH ALL COMMANDS OF  HAKRAWLER TOOL

### ISSUE THREAD

**Issue by d4715** [Zarcolio/uniqurl#1]
Hello There,

I just check your tool , it is good for used. 
but i have found issue.
in examples content of this repo you put these things.
Examples :> To get only unique URLs by hakrawler just run::>hakrawler -url google.com -plain|uniqurl
 so i just run this command and that's actual worked for me that's great.
but when i try with -all ,-js, they are not working.
i done all commands with root a/c but not got any details. 

just check these 

1) hakrawler -url google.com -all|uniqurl
![1](https://user-images.githubusercontent.com/11803332/90212225-74e18080-de10-11ea-981c-f193a82ca11e.PNG)
2)hakrawler -url google.com -js|uniqurl
![2](https://user-images.githubusercontent.com/11803332/90212318-ab1f0000-de10-11ea-99b3-6ace81df5a4b.PNG)

I hope you solved these issues.
one more thing add more examples regarding how can we  use  single use of uniqurl with direct target and also which tools support your tool with examples also so people can understand easily.

Thanks 
d4715

**Comment by Zarcolio** [comment]
Hi d4715,

Thank you for using my script!

You didn't get any results because the script expects URLs for input, that's why I use "hakrawler -plain" in my example.
I'll add some more examples.
Hope this helps :)

Zarcolio

**Comment by d4715** [comment]
Hello Zarcolio ,
 Thanks for replayed me .
i got your point 

Thanks,
d4715

**Comment by Zarcolio** [comment]
Hi,

Cool :)
Also, if you have some tool/script which gives output which contains URLs but these URLs are surrounded with text, you can use another script I wrote, grepaddr. For example:
`wget -qO - http://twitter.com|grepaddr -url|uniqurl`

**Comment by d4715** [comment]
Yeah , Thanks for this command .
Thanks 
d4715

**Comment by Zarcolio** [comment]
You're welcome 😊
